service: line-bot-lambda-ruby # NOTE: update this with your service name

provider:
  name: aws
  runtime: ruby2.5
  memorySize: 256
  region: ap-northeast-1
  environment:
    LINE_CHANNEL_SECRET: _replace_with_yours_
    LINE_CHANNEL_TOKEN: _replace_with_yours_

functions:
  webhook:
    handler: handler.webhook
    events:
      - http:
          path: /webhook
          method: post
